server:
  port: 8080
spring:
  datasource:

    password: sewell1996AabB.
    username: root
    url: jdbc:mysql://43.138.244.228:3306/site?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver


site:
  security:
    enable: true

security:
  ignore:
    urls:
      - "/1234"

